### ISSUE TITLE
Some things to add

### ISSUE THREAD

**Issue by joebowbeer** [edmondop/awesome-durable-executions#6]
Durable Computing YT channel (Golem Cloud)

https://youtube.com/@durablecomputing

Chris Riccomini blog post

https://materializedview.io/p/durable-execution-justifying-the-bubble

Golem blog post

https://www.golem.cloud/post/the-emerging-landscape-of-durable-computing

**Comment by edmondop** [comment]
Thank you @joebowbeer would you open a PR for those?
